version: '2'

services:

  configz:
    build: .
    restart: unless-stopped
    environment:
      - VAULT_ADDR=http://secretz:8200
      - ROLE=$COMPOSE_PROJECT_NAME
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - proxz:/proxZ
      - secretz:/secretZ
      - backupz:/backupZ
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: 127.0.0.1:24224
        tag: "docker.{{.Name}}"

  secretz:
    image: vault:1.8.2
    depends_on:
      - configz
    restart: unless-stopped
    command: ["server"]
    environment:
      - VAULT_ADDR=http://secretz:8200
      - VAULT_API_ADDR=http://secretz:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - secretz:/vault/config
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: 127.0.0.1:24224
        tag: "docker.{{.Name}}"
    labels:
      traefik.enable: true

  proxz:
    image: traefik:2.5
    depends_on:
      - secretz
    restart: unless-stopped
    ports:
      - 80:80 
      - 443:443
    environment:
      - CF_DNS_API_TOKEN_FILE=/etc/traefik/CF_DNS_API_TOKEN
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - proxz:/etc/traefik:ro
      - certz:/etc/certz
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: 127.0.0.1:24224
        tag: "docker.{{.Name}}"
    labels:
      traefik.enable: true
      traefik.http.routers.api.service: 'api@internal'

  portainer:
    image: portainer/portainer-ce:2.6.3
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    ports:
      - 9000:9000
      - 8000:8000
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: 127.0.0.1:24224
        tag: "docker.{{.Name}}"
    labels:
      traefik.enable: true
      traefik.http.services.portainer.loadbalancer.server.port: 9000

  fluentd:
    image: ghcr.io/izer-xyz/oci-logger:latest
    environment:
      - ORACLE_LOG_OBJECT_ID
    volumes:
      - /etc/pki/ca-trust/extracted/pem:/etc/pki/ca-trust/extracted/pem:ro
      - /run/log/journal:/var/log/journal:ro
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"

volumes:
  certz:
  secretz:
  proxz:
    driver_opts:
      type: tmpfs
      device: tmpfs
  backupz:
    driver_opts:
      type: tmpfs
      device: tmpfs
  portainer:
